# Generated by Django 5.2 on 2025-05-09 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='categorya kiriting: ')),
                ('slug', models.SlugField(verbose_name='slug uchun')),
            ],
        ),
        migrations.CreateModel(
            name='CarAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('speed', models.CharField(max_length=25)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.categorys', verbose_name='categorya tanlang')),
            ],
        ),
    ]
