# Generated by Django 5.2 on 2025-05-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carabout',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
